//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Zanshin.Domain {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Common {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Common() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Zanshin.Domain.Common", typeof(Common).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not locate the directory {0}.
        /// </summary>
        public static string DirectoryNotFound {
            get {
                return ResourceManager.GetString("DirectoryNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to public display name.
        /// </summary>
        public static string DisplayAttributeDisplayName {
            get {
                return ResourceManager.GetString("DisplayAttributeDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to email address.
        /// </summary>
        public static string DisplayAttributeEmailAddress {
            get {
                return ResourceManager.GetString("DisplayAttributeEmailAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to karma.
        /// </summary>
        public static string DisplayAttributeKarma {
            get {
                return ResourceManager.GetString("DisplayAttributeKarma", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to password.
        /// </summary>
        public static string DisplayAttributePassword {
            get {
                return ResourceManager.GetString("DisplayAttributePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tagline.
        /// </summary>
        public static string DisplayAttributeTagline {
            get {
                return ResourceManager.GetString("DisplayAttributeTagline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to subject.
        /// </summary>
        public static string DisplayAttributeTopicTitle {
            get {
                return ResourceManager.GetString("DisplayAttributeTopicTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to user name.
        /// </summary>
        public static string DisplayAttributeUserName {
            get {
                return ResourceManager.GetString("DisplayAttributeUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to please supply a password.
        /// </summary>
        public static string ErrorMessagePassword {
            get {
                return ResourceManager.GetString("ErrorMessagePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to user name is required.
        /// </summary>
        public static string ErrorMessageUserName {
            get {
                return ResourceManager.GetString("ErrorMessageUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string ExternalLoginConfirmationViewModel_Email_Email {
            get {
                return ResourceManager.GetString("ExternalLoginConfirmationViewModel_Email_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string ExternalLoginConfirmationViewModel_Password_Password {
            get {
                return ResourceManager.GetString("ExternalLoginConfirmationViewModel_Password_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} failed validation.
        ///.
        /// </summary>
        public static string FailedValidation {
            get {
                return ResourceManager.GetString("FailedValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File {0} not found. (404).
        /// </summary>
        public static string FileNotFound {
            get {
                return ResourceManager.GetString("FileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group color.
        /// </summary>
        public static string GroupColor {
            get {
                return ResourceManager.GetString("GroupColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group description.
        /// </summary>
        public static string GroupDescription {
            get {
                return ResourceManager.GetString("GroupDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group receive private messages.
        /// </summary>
        public static string GroupReceivePrivateMessages {
            get {
                return ResourceManager.GetString("GroupReceivePrivateMessages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attempted reference to HttpContext.Current which was null..
        /// </summary>
        public static string HttpContextNull {
            get {
                return ResourceManager.GetString("HttpContextNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid code..
        /// </summary>
        public static string InvalidCode {
            get {
                return ResourceManager.GetString("InvalidCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid login attempt..
        /// </summary>
        public static string InvalidLoginAttempt {
            get {
                return ResourceManager.GetString("InvalidLoginAttempt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        /// This method is a member of {0}..
        /// </summary>
        public static string ParameterNullExceptionMessageObjectIs {
            get {
                return ResourceManager.GetString("ParameterNullExceptionMessageObjectIs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The parameter {0} on method {1}..
        /// </summary>
        public static string ParameterNullExceptionMessageOnMethod {
            get {
                return ResourceManager.GetString("ParameterNullExceptionMessageOnMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The method expected a non-null, or non-default-value of the type {0}..
        /// </summary>
        public static string ParameterNullExceptionMethodExpectedNonNull {
            get {
                return ResourceManager.GetString("ParameterNullExceptionMethodExpectedNonNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  No parameter name passed, however the following parameters were available at the time the exception was thrown:
        ///.
        /// </summary>
        public static string ParameterNullExceptionNoName {
            get {
                return ResourceManager.GetString("ParameterNullExceptionNoName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Unable to determine the failing parameter type, perhaps the name passed was incorrect? .
        /// </summary>
        public static string ParameterNullExceptionUnableToDetermine {
            get {
                return ResourceManager.GetString("ParameterNullExceptionUnableToDetermine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Unable to determine the method&apos;s declaring type..
        /// </summary>
        public static string ParameterNullExceptionUnableToDetermineDeclaringType {
            get {
                return ResourceManager.GetString("ParameterNullExceptionUnableToDetermineDeclaringType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remember me?.
        /// </summary>
        public static string RememberMe {
            get {
                return ResourceManager.GetString("RememberMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subject is requried..
        /// </summary>
        public static string SubjectIsRequried {
            get {
                return ResourceManager.GetString("SubjectIsRequried", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User with the id {0} could not be found.
        /// </summary>
        public static string UserWithIdNotFound {
            get {
                return ResourceManager.GetString("UserWithIdNotFound", resourceCulture);
            }
        }
    }
}
